Repository woowacourse-teams/2024-momo, pull requests merged in 2024-10, with the labels that each got.

#385 [FE] BottomFixedButton 버그 수정
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/mocks/meeting/meetingHandlers.ts
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
Labels: 🐈 프론트엔드, 🐞 버그

#356 [FE] 약속 생성 흐름에 퍼널 패턴 적용
  frontend/src/components/_common/Buttons/BottomFixedButton/BottomFixedButton.styles.ts
  frontend/src/components/_common/Buttons/BottomFixedButton/index.tsx
  frontend/src/constants/inputFields.ts
  frontend/src/constants/meeting.ts
  frontend/src/hooks/useButtonOnKeyboard/useButtonOnKeyboard.ts
  frontend/src/hooks/useCreateMeeting/useCreateMeeting.ts
  frontend/src/hooks/useFunnel/FunnelMain.tsx
  frontend/src/hooks/useFunnel/useFunnel.tsx
  frontend/src/hooks/useFunnel/useFunnel.type.ts
  frontend/src/hooks/useInput/useInput.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.ts
  frontend/src/pages/CreateMeetingFunnelPage/MeetingDateTime.tsx
  frontend/src/pages/CreateMeetingFunnelPage/MeetingHostInfo.tsx
  frontend/src/pages/CreateMeetingFunnelPage/MeetingName.tsx
  frontend/src/pages/CreateMeetingFunnelPage/index.tsx
  frontend/src/styles/global.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#393 [FE] 약속 퍼널 패턴 인터페이스 통합
  frontend/src/hooks/useCreateMeeting/useCreateMeeting.ts
  frontend/src/hooks/useDateSelect/useDateSelect.ts
  frontend/src/pages/CreateMeetingFunnelPage/MeetingDateTime.tsx
  frontend/src/pages/CreateMeetingFunnelPage/index.tsx
  frontend/src/pages/CreateMeetingPage/CreateMeetingPage.styles.ts
  frontend/src/pages/CreateMeetingPage/MeetingDateTime.tsx
  frontend/src/pages/CreateMeetingPage/MeetingHostInfo.tsx
  frontend/src/pages/CreateMeetingPage/MeetingName.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#391 [FE] 토스트 UI 구현
  frontend/src/assets/images/attendeeCheck.svg
  frontend/src/assets/images/check.svg
  frontend/src/assets/images/exclamation.svg
  frontend/src/components/_common/Toast/Toast.stories.tsx
  frontend/src/components/_common/Toast/Toast.styles.ts
  frontend/src/components/_common/Toast/Toast.type.ts
  frontend/src/components/_common/Toast/ToastContainer.tsx
  frontend/src/components/_common/Toast/ToastList/ToastList.styles.ts
  frontend/src/components/_common/Toast/ToastList/ToastList.tsx
  frontend/src/components/_common/Toast/index.tsx
  frontend/src/contexts/ToastProvider.tsx
  frontend/src/hooks/useToast/useToast.ts
  frontend/src/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인, 🧪 테스트

#397 [FE] '약속 후보 날짜 선택'과 '약속 시간 범위 선택' 사이에 간격을 설정
  frontend/src/assets/images/logoSunglass.svg
  frontend/src/pages/CreateMeetingPage/components/MeetingDateTime/MeetingDateTime.styles.ts
  frontend/src/pages/CreateMeetingPage/components/MeetingDateTime/index.tsx
  frontend/src/pages/CreateMeetingPage/components/MeetingHostInfo/index.tsx
  frontend/src/pages/CreateMeetingPage/components/MeetingName/index.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🎨 디자인, ♻️ 리팩터링

#383 [FE] 달력 테스트 코드 작성
  frontend/jest.config.js
  frontend/src/hooks/useCalendar/useCalendar.test.ts
  frontend/src/hooks/useCalendar/useCalendar.ts
  frontend/src/hooks/useCalendar/useCalendar.utils.test.ts
  frontend/src/hooks/useCalendar/useCalendar.utils.ts
Labels: 🐈 프론트엔드, 🧪 테스트

#403 [FE] 약속 입장 페이지 구현 및 바로 약속 등록하기 페이지에서 바로 드래그/클릭으로 약속 등록이 가능하게 구현
  frontend/src/apis/meetings/confirms.ts
  frontend/src/apis/meetings/meetings.ts
  frontend/src/apis/meetings/recommends.ts
  frontend/src/apis/schedules.ts
  frontend/src/components/MeetingConfirmCalendar/Picker/index.tsx
  frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
  frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useCalendarPick/useCalendarPick.tsx
  frontend/src/hooks/useCreateMeeting/useCreateMeeting.ts
  frontend/src/hooks/useMeetingTimeRecommendFilter/useMeetingTimeRecommendFilter.ts
  frontend/src/hooks/useMeetingType/useMeetingType.ts
  frontend/src/layouts/GlobalLayout.tsx
  frontend/src/mocks/data.json
  frontend/src/mocks/meeting/data/meetingEntranceDateTimeInfo.json
  frontend/src/mocks/meeting/data/meetingEntranceDaysOnlyInfo.json
  frontend/src/mocks/meeting/data/meetingTableFrame.json
  frontend/src/mocks/meeting/handlers.ts
  frontend/src/mocks/meeting/meetingHandlers.ts
  frontend/src/pages/FixedMeetingTicketPage/components/ActionButtonGroup/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/index.tsx
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions/index.tsx
  frontend/src/pages/MeetingConfirmPage/index.tsx
  frontend/src/pages/MeetingEntrancePage/MeetingEntrancePage.styles.ts
  frontend/src/pages/MeetingEntrancePage/index.tsx
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/pages/MeetingRegisterPage/MeetingRegisterPage.styles.ts
  frontend/src/pages/MeetingRegisterPage/index.tsx
  frontend/src/pages/MeetingViewerPage/MeetingViewerPage.styles.ts
  frontend/src/pages/MeetingViewerPage/index.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/confirm/mutations.ts
  frontend/src/stores/servers/confirm/queries.ts
  frontend/src/stores/servers/meeting/mutations.ts
  frontend/src/stores/servers/meeting/queries.ts
  frontend/src/stores/servers/schedule/mutations.ts
  frontend/src/stores/servers/schedule/queries.ts
  frontend/src/types/schedule.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인, ♻️ 리팩터링

#400 [FE] 날짜만 입력 시, 약속 추천 필터링 기능 제거
  frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx
Labels: 🐈 프론트엔드, ♻️ 리팩터링

#408 [ALL] 자바스크립트 번들 파일이 중복으로 생기는 문제 해결
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#409 [ALL] 프론트엔드 워크플로우 변경사항 develop 브랜치에 적용
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
  frontend/src/mocks/meeting/data/mySchedule.json
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#414 [FE] 약속 생성 확인 모달 복구
  frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/MeetingCreationConfirmModal.styles.ts
  frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/index.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#415 [FE] 약속 생성 확인 모달 복구 develop 브랜치에 적용
  frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/MeetingCreationConfirmModal.styles.ts
  frontend/src/pages/CreateMeetingPage/components/MeetingCreationConfirmModal/index.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#411 [FE] 헤더 뒤로가기 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/attendeeCheck.svg
  frontend/src/assets/images/back.svg
  frontend/src/assets/images/share.svg
  frontend/src/components/MeetingConfirmCalendar/Picker/index.tsx
  frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
  frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/ScheduleViewer/ScheduleTable.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/components/_common/Buttons/BackButton/index.tsx
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/components/_common/Toast/ToastList/ToastList.styles.ts
  frontend/src/contexts/AuthProvider.tsx
  frontend/src/contexts/UuidProvider.tsx
  frontend/src/hooks/useFunnel/useFunnel.tsx
  frontend/src/hooks/useRouter/useRouter.ts
  frontend/src/layouts/ContentLayout/ContentLayout.style.ts
  frontend/src/layouts/ContentLayout/index.tsx
  frontend/src/layouts/GlobalLayout/GlobalLayout.styles.ts
  frontend/src/layouts/GlobalLayout/index.tsx
  frontend/src/layouts/UuidLayout/index.tsx
  frontend/src/mocks/meeting/meetingHandlers.ts
  frontend/src/pages/AttendeeLoginPage/index.tsx
  frontend/src/pages/CreateMeetingPage/components/MeetingDateTime/MeetingDateTime.styles.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/UnconfirmedMessage/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/MeetingConfirmPage/MeetingTimeConfirmPage.styles.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions/index.tsx
  frontend/src/pages/MeetingConfirmPage/index.tsx
  frontend/src/pages/MeetingEntrancePage/index.tsx
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/pages/MeetingRecommendPage/MeetingRecommendPage.styles.ts
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/pages/MeetingRegisterPage/index.tsx
  frontend/src/pages/MeetingViewerPage/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/confirm/mutations.ts
  frontend/src/stores/servers/meeting/mutations.ts
  frontend/src/stores/servers/schedule/mutations.ts
  frontend/src/stores/servers/user/mutations.ts
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#421 [FE] 약속 입장, 약속 현황 조회 페이지(달력)의 웹 접근성을 개선
  frontend/.eslintrc.json
  frontend/.storybook/preview.tsx
  frontend/legacy/components/AllSchedules/AllSchdules.utils.ts
  frontend/src/assets/images/logo.svg
  frontend/src/assets/images/logo.webp
  frontend/src/assets/images/logoSunglass.svg
  frontend/src/assets/images/logoSunglass.webp
  frontend/src/components/MeetingCalendar/Date/Date.utils.ts
  frontend/src/components/MeetingConfirmCalendar/Header/index.tsx
  frontend/src/components/MeetingConfirmCalendar/Picker/index.tsx
  frontend/src/components/MeetingConfirmCalendar/SingleDate/SingleDateViewer.tsx
  frontend/src/components/MeetingConfirmCalendar/SingleDate/index.tsx
  frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
  frontend/src/components/MeetingConfirmCalendar/WeekDays.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/components/Schedules/Schedules.util.ts
  frontend/src/components/_common/Buttons/BackButton/index.tsx
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/components/_common/Calendar/Body/index.tsx
  frontend/src/components/_common/Calendar/Calendar.stories.tsx
  frontend/src/components/_common/Calendar/index.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/components/_common/ScreenReaderOnly/ScreenReaderOnly.styles.ts
  frontend/src/components/_common/ScreenReaderOnly/index.tsx
  frontend/src/components/_common/Text/Accent/index.tsx
  frontend/src/components/_common/Text/index.tsx
  frontend/src/constants/date.ts
  frontend/src/hooks/useCalendar/useCalendar.ts
  frontend/src/mocks/meeting/data/meetingAllSchedules.json
  frontend/src/pages/MeetingEntrancePage/index.tsx
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/pages/MeetingViewerPage/index.tsx
  frontend/src/types/calendar.ts
  frontend/src/types/images.d.ts
  frontend/src/utils/a11y.ts
  frontend/src/utils/date.ts
  frontend/webpack.common.js
Labels: 🐈 프론트엔드

#419 [FE] 클라이언트 영역 에러 핸들링 개선 (토스트 UI)
  frontend/src/apis/_common/fetchClient.ts
  frontend/src/apis/_common/fetcher.ts
  frontend/src/apis/meetings/confirms.ts
  frontend/src/apis/meetings/meetings.ts
  frontend/src/apis/meetings/recommends.ts
  frontend/src/apis/schedules.ts
  frontend/src/apis/users.ts
  frontend/src/components/ErrorToastNotifier/index.tsx
  frontend/src/components/QueryClientManager/index.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/components/_common/Modal/MeetingLockConfirmModal/index.tsx
  frontend/src/contexts/AuthProvider.tsx
  frontend/src/contexts/ErrorProvider.tsx
  frontend/src/hooks/useErrorDispatch/useErrorDispatch.ts
  frontend/src/hooks/useErrorState/useErrorState.ts
  frontend/src/index.tsx
  frontend/src/stores/servers/meeting/mutations.ts
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#422 [FE] 캐러셀을 적용한 랜딩 페이지 디자인 수정
  frontend/src/assets/images/carousel-first.png
  frontend/src/assets/images/carousel-fourth.png
  frontend/src/assets/images/carousel-second.png
  frontend/src/assets/images/carousel-third.png
  frontend/src/components/ComponentCarousel/CompnentCarousel.styles.ts
  frontend/src/components/ComponentCarousel/index.tsx
  frontend/src/components/LandingCarousel/FirstCarousel.tsx
  frontend/src/components/LandingCarousel/FourthCarousel.tsx
  frontend/src/components/LandingCarousel/LandingCarousels.styles.ts
  frontend/src/components/LandingCarousel/SecondCarousel.tsx
  frontend/src/components/LandingCarousel/ThirdCarousel.tsx
  frontend/src/components/_common/Text/Text.styles.ts
  frontend/src/components/_common/Text/index.tsx
  frontend/src/pages/LandingPage/index.tsx
Labels: 🐈 프론트엔드, 🎨 디자인

#426 [FE] 달력 확정 페이지 ConfirmModal 추가 및 로그인 후 라우팅 경로 수정
  frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
  frontend/src/stores/servers/user/mutations.ts
Labels: 🐈 프론트엔드, 🛠️ 픽스

#428 [FE] 약속 생성 플레이스홀더, 캐러셀 이동 속도 수정
  frontend/src/components/ComponentCarousel/index.tsx
  frontend/src/components/_common/Buttons/BottomFixedButton/BottomFixedButton.styles.ts
  frontend/src/constants/inputFields.ts
Labels: 🐈 프론트엔드, 🥵 핫픽스

#430 [FE] 달력 확정 페이지에서도 약속 잠금 모달을 사용할 수 있도록 수정
  frontend/src/components/MeetingConfirmCalendar/Viewer/index.tsx
  frontend/src/stores/servers/user/mutations.ts
Labels: 🐈 프론트엔드, 🥵 핫픽스
