Repository woowacourse-teams/2024-momo, pull requests merged in 2024-07, with the labels that each got.

#2 [ALL] 모모, 안녕?
  README.md
  backend/.gitkeep
  frontend/.gitkeep
Labels: 프론트엔드, 백엔드, ⚙️ 환경설정, (ノಠ益ಠ)ノ彡┻━┻, 🍶 술 먹고 싶음

#7 [BE] 개발 환경 설정
  .gitignore
  backend/.gitkeep
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/woowacourse/momo/MomoApplication.java
Labels: 백엔드, ⚙️ 환경설정, 💣 (╮°-°)╮┳━┳, 😭 배고픔

#9 [BE] Entity 설계
  backend/src/main/java/com/woowacourse/momo/MomoApplication.java
  backend/src/main/java/com/woowacourse/momo/domain/BaseEntity.java
  backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDate.java
  backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/Guest.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/GuestRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
  backend/src/main/java/com/woowacourse/momo/domain/meeting/MeetingRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/TimeSlotRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
Labels: 백엔드, 기능, 🏡 집 가고 싶음

#12 [BE] API 공통 응답 객체 정의
  .gitignore
  backend/src/main/java/com/woowacourse/momo/controller/MomoApiResponse.java
Labels: 백엔드, 기능, 🏡 집 가고 싶음

#14 [BE] Meeting Entity 내 필드 추가
  backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
Labels: 백엔드, 기능

#18 [BE] CORS Config 추가
  backend/src/main/java/com/woowacourse/momo/config/CorsConfig.java
Labels: 백엔드, 기능

#19 [BE] 타임슬롯 도메인을 테이블에서 enum타입으로 수정
  backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/TimeSlotRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
Labels: 백엔드, ♻️ 리팩터링

#20 [BE] 가능 시간 추가 API 구현
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/Guest.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/GuestName.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/GuestRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/DateTimesCreateRequest.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleCreateRequest.java
  backend/src/test/java/com/woowacourse/momo/domain/guest/GuestNameTest.java
Labels: 백엔드, 기능

#21 [BE] 미팅 기본 정보 조회 API 구현
  backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
  backend/src/main/java/com/woowacourse/momo/domain/availabledate/AvailableDateRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/meeting/MeetingRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/dto/ScheduleTimeResponse.java
  backend/src/main/java/com/woowacourse/momo/domain/timeslot/Timeslot.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
Labels: 백엔드, 기능

#25 [FE] import 순서 설정 및 자동 정렬 & 절대 경로 설정
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/getMeeting.ts
  frontend/src/apis/getSchedule.ts
  frontend/src/apis/postSchedule.ts
  frontend/src/components/TimePicker/TimePicker.styles.ts
  frontend/src/components/TimePicker/index.tsx
  frontend/src/components/_common/Button/Button.styles.ts
  frontend/src/components/_common/Button/index.tsx
  frontend/src/hooks/useTimePick/useTimePick.ts
  frontend/src/index.tsx
  frontend/src/layouts/GlobalLayout.tsx
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/router.tsx
  frontend/src/types/.gitkeep
  frontend/src/types/styles/theme.d.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: 프론트엔드, ⚙️ 환경설정

#27 [BE] 도메인 설계 수정 반영
  backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/Attendee.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeName.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/Role.java
  backend/src/main/java/com/woowacourse/momo/domain/guest/GuestRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingResponse.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleCreateRequest.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleTimeResponse.java
  backend/src/test/java/com/woowacourse/momo/domain/attendee/AttendeeNameTest.java
  backend/src/test/java/com/woowacourse/momo/domain/guest/GuestNameTest.java
  backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
Labels: 백엔드, 기능

#29 [BE] 커스텀 예외 및 에러코드 인터페이스 추가
  backend/src/main/java/com/woowacourse/momo/exception/MomoException.java
  backend/src/main/java/com/woowacourse/momo/exception/code/ErrorCodeType.java
Labels: 백엔드, 기능

#32 [FE] 스토리북, RTL, msw 사용을 위한 환경설정
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/_common/Button/Button.stories.tsx
  frontend/src/mocks/server.ts
  frontend/tsconfig.json
Labels: 프론트엔드, ⚙️ 환경설정

#42 [BE] 비회원 로그인 기능 추가
  backend/build.gradle
  backend/src/main/java/com/woowacourse/momo/auth/JwtManager.java
  backend/src/main/java/com/woowacourse/momo/auth/dto/TokenInfo.java
  backend/src/main/java/com/woowacourse/momo/controller/attendee/AttendeeController.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/Attendee.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeePassword.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
  backend/src/main/java/com/woowacourse/momo/domain/meeting/Meeting.java
  backend/src/main/java/com/woowacourse/momo/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/woowacourse/momo/exception/MomoException.java
  backend/src/main/java/com/woowacourse/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/com/woowacourse/momo/exception/code/AuthErrorCode.java
  backend/src/main/java/com/woowacourse/momo/exception/code/ErrorCodeType.java
  backend/src/main/java/com/woowacourse/momo/service/attendee/AttendeeService.java
  backend/src/main/java/com/woowacourse/momo/service/attendee/dto/AttendeeLoginRequest.java
  backend/src/main/java/com/woowacourse/momo/service/attendee/dto/TokenResponse.java
  backend/src/test/java/com/woowacourse/momo/auth/JwtManagerTest.java
  backend/src/test/java/com/woowacourse/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/com/woowacourse/momo/domain/attendee/AttendeeNameTest.java
  backend/src/test/java/com/woowacourse/momo/domain/attendee/AttendeePasswordTest.java
  backend/src/test/java/com/woowacourse/momo/domain/attendee/AttendeeTest.java
  backend/src/test/java/com/woowacourse/momo/fixture/MeetingFixture.java
  backend/src/test/java/com/woowacourse/momo/service/attendee/AttendeeServiceTest.java
  backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
  backend/src/test/java/com/woowacourse/momo/support/DatabaseCleanupListener.java
  backend/src/test/java/com/woowacourse/momo/support/IsolateDatabase.java
Labels: 백엔드, 기능, 🧪 테스트

#45 [FE] Webpack에서 Assets 파일(image, SVG, font)을 빌드할 수 있도록 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/types/images.d.ts
  frontend/webpack.common.js
Labels: 프론트엔드, ⚙️ 환경설정

#40 [FE] ci 워크플로우 구축
  .github/workflows/frontend-ci.yml
  frontend/package-lock.json
  frontend/package.json
Labels: 프론트엔드, ⚙️ 환경설정

#52 [BE] 약속 생성 결과 조회 API 구현
  backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
  backend/src/main/java/com/woowacourse/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingSharingResponse.java
  backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/com/woowacourse/momo/fixture/AttendeeFixture.java
  backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
Labels: 백엔드, 기능

#64 [FE] Input, Field 컴포넌트 구현
  frontend/src/components/_common/Field/Field.stories.tsx
  frontend/src/components/_common/Field/Field.styles.ts
  frontend/src/components/_common/Field/index.tsx
  frontend/src/components/_common/Input/Input.stories.tsx
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/components/_common/Input/index.tsx
  frontend/src/hooks/useInput/useInput.ts
Labels: 프론트엔드, 🚀 기능

#63 [FE] 헤더 컴포넌트 구현
  frontend/src/assets/images/logo.svg
  frontend/src/assets/images/menu.svg
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/layouts/GlobalLayout.tsx
  frontend/tsconfig.json
Labels: 프론트엔드, 🚀 기능

#68 [FE]: 날짜를 선택할 수 있는 캘린더 UI 구현
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/src/components/_common/Calendar/Calendar.stories.tsx
  frontend/src/components/_common/Calendar/Calendar.styles.ts
  frontend/src/components/_common/Calendar/index.tsx
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.ts
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
  frontend/src/hooks/useTimePick/useTimePick.utils.ts
  frontend/src/styles/global.ts
Labels: 프론트엔드, 🚀 기능, 🎨 디자인

#71 [FE] Dropdown 컴포넌트 제작 및 시간 선택 hook 구현
  frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/_common/Dropdown/Dropdown.styles.ts
  frontend/src/components/_common/Dropdown/index.tsx
  frontend/src/hooks/useTimeRangeDropdown/constants.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
Labels: 프론트엔드, 🚀 기능

#81 [BE] 기존 약속 정보 조회 API 응답에 참가자들의 정보 추가
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/com/woowacourse/momo/service/meeting/MeetingServiceTest.java
Labels: 백엔드, 🚀 기능

#79 [BE] 단일 참가자의 스케줄 조회 로직 추가
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleDateTimesResponse.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleOneAttendeeResponse.java
  backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java
Labels: 백엔드, 🚀 기능

#86 [BE] 참가자 스케줄 조회 반환 값 내 시간 포멧팅 수정
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/ScheduleDateTimesResponse.java
Labels: 백엔드, ♻️ 리팩터링

#87 [BE] 약속 생성 API에서 바디를 통해 uuid를 제공
  backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
  backend/src/main/java/com/woowacourse/momo/service/meeting/MeetingService.java
Labels: 백엔드, ♻️ 리팩터링

#85 [BE] 모든 참여자 약속 조회 API를 구현합니다.
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/Schedule.java
  backend/src/main/java/com/woowacourse/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/AttendeesScheduleResponse.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/dto/SchedulesResponse.java
  backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java
Labels: 백엔드, 🚀 기능, ♻️ 리팩터링

#91 [FE] 구현한 컴포넌트를 바탕으로 약속 생성 페이지를 연결
  frontend/src/apis/getMeeting.ts
  frontend/src/apis/meetings.ts
  frontend/src/apis/schedule.ts
  frontend/src/components/Time/Picker/TimePicker.util.ts
  frontend/src/components/Time/Picker/index.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/components/_common/Field/Field.stories.tsx
  frontend/src/components/_common/Field/Field.styles.ts
  frontend/src/components/_common/Field/index.tsx
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
  frontend/src/hooks/useTimeRangeDropdown/constants.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/pages/CreateMeetingPage/CreateMeetingPage.styles.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/meeting/mutation.ts
  frontend/src/stores/servers/meeting/queries.ts
  frontend/src/stores/servers/schedule/mutations.ts
  frontend/webpack.common.js
Labels: 프론트엔드, 🚀 기능, (ノಠ益ಠ)ノ彡┻━┻

#96 [BE] ArguementResolver를 구현하여 사용자 인증 책임을 컨트롤러로부터 분리
  backend/src/main/java/com/woowacourse/momo/auth/dto/TokenInfo.java
  backend/src/main/java/com/woowacourse/momo/config/WebConfig.java
  backend/src/main/java/com/woowacourse/momo/controller/auth/AuthArgumentResolver.java
  backend/src/main/java/com/woowacourse/momo/controller/auth/AuthAttendee.java
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/com/woowacourse/momo/domain/attendee/AttendeeRepository.java
  backend/src/main/java/com/woowacourse/momo/exception/code/AuthErrorCode.java
  backend/src/main/java/com/woowacourse/momo/service/attendee/AttendeeService.java
  backend/src/main/java/com/woowacourse/momo/service/auth/JwtManager.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/com/woowacourse/momo/service/auth/JwtManagerTest.java
  backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java
Labels: 백엔드, 🚀 기능

#98 [FE] 약속 현황 조회, 수정 페이지 구현
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/fetchClient.ts
  frontend/src/apis/getHeaders.ts
  frontend/src/apis/getMeetingFrame.ts
  frontend/src/apis/getMeetingSchedules.ts
  frontend/src/apis/postSchedule.ts
  frontend/src/apis/schedule.ts
  frontend/src/components/Time/Picker/TimePicker.util.ts
  frontend/src/components/Time/Picker/TimePickerContainer.tsx
  frontend/src/components/Time/Picker/index.tsx
  frontend/src/components/Time/Time.styles.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useTimePick/useTimePick.ts
  frontend/src/hooks/useTimePick/useTimePick.utils.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/meeting/data/meetingAllSchedules.json
  frontend/src/mocks/meeting/data/meetingTableFrame.json
  frontend/src/mocks/meeting/data/oneAttendeeSchedule.json
  frontend/src/mocks/meeting/handlers.ts
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/stores/servers/meeting/queries.ts
  frontend/src/stores/servers/schedule/mutations.ts
  frontend/src/types/meeting.ts
Labels: 프론트엔드, 🚀 기능, 🎨 디자인, ⚙️ 환경설정

#100 [FE] 비회원 로그인 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/attendee.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.styles.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/utils/cookies.ts
Labels: 🚀 기능, 🎨 디자인

#99 [BE] JWT 토큰을 통해 자신의 스케줄을 조회할 수 있는 기능 추가
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/com/woowacourse/momo/service/schedule/ScheduleService.java
  backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/com/woowacourse/momo/service/schedule/ScheduleServiceTest.java
Labels: 백엔드, 🚀 기능, 🧪 테스트

#107 [ALL] RESTful API 디자인 원칙에 기반하여 기존 API path를 수정
  backend/src/main/java/com/woowacourse/momo/controller/attendee/AttendeeController.java
  backend/src/main/java/com/woowacourse/momo/controller/meeting/MeetingController.java
  backend/src/main/java/com/woowacourse/momo/controller/schedule/ScheduleController.java
  backend/src/test/java/com/woowacourse/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/com/woowacourse/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/com/woowacourse/momo/controller/schedule/ScheduleControllerTest.java
Labels: 프론트엔드, 백엔드, ♻️ 리팩터링

#109 [ALL] 작업 현황을 디스코드로 알림을 받기 위한 yml 파일 생성, 설정
  .github/workflows/discord-issue.yml
  .github/workflows/discord-pull-request.yml
  .github/workflows/discord-review.yml
Labels: 프론트엔드, 백엔드, ⚙️ 환경설정

#105 [FE] 비회원 로그인 페이지와 약속 조회/수정 페이지를 연결
  frontend/src/apis/getHeaders.ts
  frontend/src/apis/getMeetingFrame.ts
  frontend/src/apis/postSchedule.ts
  frontend/src/components/Time/Picker/TimePickerContainer.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/constants/cookies.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.styles.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/schedule/mutations.ts
Labels: 프론트엔드, 🚀 기능, 🏡 집 가고 싶음

#123 [ALL] 작업 현황 디스코드 알림 yml 파일 개선
  .github/workflows/discord-issue.yml
  .github/workflows/discord-pull-request.yml
  .github/workflows/discord-review.yml
Labels: ⚙️ 환경설정, (ノಠ益ಠ)ノ彡┻━┻

#119 [BE] 약속 잠금 API 추가
  backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/domain/attendee/Role.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/RoleTest.java
  backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, ♻️ 리팩터링
