Repository woowacourse-teams/2024-momo, pull requests merged in 2024-08, with the labels that each got.

#127 [BE] 약속 잠금 해제 기능 추가
  backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#131 [BE] 기존 jwt 토큰 응답 방식을 쿠키로 변경하고 path 및 보안 설정
  backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
  backend/src/main/java/kr/momo/controller/auth/AuthArgumentResolver.java
  backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
  backend/src/main/java/kr/momo/service/attendee/dto/TokenResponse.java
  backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/service/auth/JwtManagerTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#140 [FE] API 명세 수정에 따른 변경사항 반영
  frontend/src/apis/_common/fetchClient.ts
  frontend/src/apis/_common/getHeaders.ts
  frontend/src/apis/attendee.ts
  frontend/src/apis/fetchClient.ts
  frontend/src/apis/getMeetingFrame.ts
  frontend/src/apis/getMeetingSchedules.ts
  frontend/src/apis/meetings.ts
  frontend/src/apis/postSchedule.ts
  frontend/src/apis/schedules.ts
  frontend/src/components/Time/Picker/TimePicker.util.ts
  frontend/src/components/Time/Picker/TimePickerContainer.tsx
  frontend/src/components/Time/Picker/index.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/cookies.ts
  frontend/src/index.tsx
  frontend/src/mocks/meeting/handlers.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/stores/servers/meeting/queries.ts
  frontend/src/stores/servers/schedule/mutations.ts
  frontend/src/types/meeting.ts
Labels: 🐈 프론트엔드, ♻️ 리팩터링

#146 [BE] 쿠키 헤더의 SameSite 옵션을 None으로 변경
  backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
Labels: 🐈‍⬛ 백엔드, 🐞 버그

#129 [FE] colors, typography 디자인 토큰 생성
  frontend/src/components/_common/Button/Button.styles.ts
  frontend/src/components/_common/Calendar/Calendar.styles.ts
  frontend/src/components/_common/TimeSlot/TimeSlot.styles.ts
  frontend/src/pages/CreateMeetingPage/CreateMeetingPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/tokens/colors.ts
  frontend/src/styles/tokens/typography.ts
  frontend/src/types/styles/theme.d.ts
Labels: 🐈 프론트엔드, 🎨 디자인

#147 [ALL] 서비스 소개글 작성
  README.md
Labels: 🐈 프론트엔드, 🐈‍⬛ 백엔드, 📄 문서

#150 [BE] 미팅 조회 시 날짜 정보를 정렬하여 반환하도록 수정
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDateRepository.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
Labels: 🐈‍⬛ 백엔드, 🛠️ 픽스

#149 [BE] 약속 생성시 과거 날짜 검증 추가
  backend/src/main/java/kr/momo/config/TimeConfig.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDate.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/availabledate/AvailableDateTest.java
  backend/src/test/java/kr/momo/domain/availabledate/AvailableDatesTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#165 [BE] CORS, Cookie 설정 오류 수정
  backend/src/main/java/kr/momo/config/CorsConfig.java
  backend/src/main/java/kr/momo/controller/CookieManager.java
Labels: 🐈‍⬛ 백엔드, 🛠️ 픽스

#128 [BE] 약속 일정 확정 API 추가
  backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/domain/attendee/Role.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDate.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeetingRepository.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/domain/timeslot/TimeslotInterval.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmRequest.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmResponse.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/RoleTest.java
  backend/src/test/java/kr/momo/domain/availabledate/AvailableDatesTest.java
  backend/src/test/java/kr/momo/domain/timeslot/TimeslotIntervalTest.java
  backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
  backend/src/test/java/kr/momo/fixture/MeetingFixture.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#154 [FE] 버튼 컴포넌트 재구성
  frontend/src/components/Time/Picker/index.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/components/_common/Button/Button.stories.tsx
  frontend/src/components/_common/Button/Button.styles.ts
  frontend/src/components/_common/Button/index.tsx
  frontend/src/components/_common/Calendar/Calendar.stories.tsx
  frontend/src/types/styles/theme.d.ts
Labels: 🐈 프론트엔드, 🎨 디자인, ♻️ 리팩터링

#158 [FE] 공용 토글 버튼 컴포넌트 구현
  frontend/src/components/_common/Buttons/Button/Button.stories.tsx
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/components/_common/Buttons/ToggleButton/ToggleButton.stories.tsx
  frontend/src/components/_common/Buttons/ToggleButton/ToggleButton.styles.ts
  frontend/src/components/_common/Buttons/ToggleButton/index.tsx
  frontend/src/components/_common/Header/Header.styles.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#175 [BE] 컨테이너에 로그 폴더 마운트 볼륨 추가
  .github/workflows/backend-cd.yml
Labels: 🐈‍⬛ 백엔드, ⚙️ 환경설정

#178 [BE] Docker 컨테이너 포트포워드 인자 수정
  .github/workflows/backend-cd.yml
Labels: 🐈‍⬛ 백엔드, ⚙️ 환경설정, 🐳 인프라

#188 [FE] 시간 선택 옵션 수정
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🐞 버그

#171 [FE] 에러 트래킹을 위한 Sentry 환경 구축, 사용자 행동 분석을 위한 GA 환경 구축
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/index.tsx
  frontend/webpack.common.js
Labels: 🐈 프론트엔드, ⚙️ 환경설정, 🏡 집 가고 싶음

#159 [FE] 비회원 로그인 로직을 백엔드의 쿠키 기반 인증 방식에 맞게 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/_common/fetchClient.ts
  frontend/src/apis/_common/getHeaders.ts
  frontend/src/apis/attendee.ts
  frontend/src/apis/meetings.ts
  frontend/src/apis/schedules.ts
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/constants/cookies.ts
  frontend/src/contexts/AuthProvider.tsx
  frontend/src/layouts/GlobalLayout.tsx
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/meeting/mutation.ts
  frontend/src/utils/auth.ts
  frontend/src/utils/cookies.ts
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#139 [BE] 약속 추천 기능 구현
  backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
  backend/src/main/java/kr/momo/domain/schedule/Schedule.java
  backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/kr/momo/exception/code/ScheduleErrorCode.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/main/java/kr/momo/service/schedule/dto/RecommendedScheduleResponse.java
  backend/src/main/java/kr/momo/service/schedule/dto/SchedulesResponse.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeeGroupTest.java
  backend/src/test/java/kr/momo/fixture/AvailableDateFixture.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, 💣 (╮°-°)╮┳━┳

#183 [BE] 미팅에 속하는 모든 참여자의 이름을 조회하는 API
  backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
  backend/src/main/java/kr/momo/controller/attendee/AttendeeControllerDocs.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
  backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/kr/momo/service/attendee/AttendeeServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#169 [BE] 약속 확정 취소 기능 구현
  backend/src/main/java/kr/momo/controller/annotation/ApiSuccessResponse.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeetingRepository.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/fixture/ConfirmedMeetingFixture.java
  backend/src/test/java/kr/momo/fixture/MeetingFixture.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#156 [FE] 특정 테이블 셀에 마우스를 올리거나, 클릭하면 해당 셀을 선택한 약속 참여자들을 확인할 수 있는 툴팁 컴포넌트 구현
  frontend/.storybook/main.ts
  frontend/legacy/components/AllSchedules/AllSchdules.styles.ts
  frontend/legacy/components/AllSchedules/AllSchdules.utils.ts
  frontend/legacy/components/AllSchedules/index.tsx
  frontend/legacy/components/AttendeeTooltip/AttendeeTooltip.styles.ts
  frontend/legacy/components/AttendeeTooltip/index.tsx
  frontend/legacy/components/ScrollPreserving/index.tsx
  frontend/legacy/components/Tooltip/Tooltip.styles.ts
  frontend/legacy/components/Tooltip/index.tsx
  frontend/legacy/hooks/useScheduleTooltip/useScheduleTooltip.ts
  frontend/legacy/hooks/useScheduleTooltip/useScheduleTooltip.utils.ts
  frontend/legacy/hooks/useTooltip/useTooltip.ts
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.stories.tsx
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.styles.ts
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
  frontend/src/components/AttendeeTooltip/index.tsx
  frontend/src/components/Schedules/AllSchedule.tsx
  frontend/src/components/Schedules/Picker/SchedulePicker.utils.ts
  frontend/src/components/Schedules/Picker/SchedulePickerContainer.tsx
  frontend/src/components/Schedules/Picker/index.tsx
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/components/Schedules/Schedules.util.ts
  frontend/src/components/Schedules/SchedulesViewer.tsx
  frontend/src/components/Schedules/SingleSchedule.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Tooltip/Tooltip.stories.tsx
  frontend/src/components/_common/Tooltip/Tooltip.styles.ts
  frontend/src/components/_common/Tooltip/index.tsx
  frontend/src/hooks/useDatePage/useDatePage.ts
  frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
  frontend/src/hooks/useSelectSchedule/useSelectSchedule.ts
  frontend/src/hooks/useTimePick/useTimePick.ts
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/mocks/meeting/data/meetingAllSchedules.json
  frontend/src/mocks/meeting/data/meetingSingleSchedule.json
  frontend/src/mocks/meeting/data/meetingTableFrame.json
  frontend/src/mocks/meeting/handlers.ts
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/types/tooltip.ts
Labels: 🐈 프론트엔드, 🎨 디자인, 🧪 테스트

#189 [FE] 약속 추천 페이지, 약속 결정 페이지 구현
  frontend/src/apis/mettingRecommend.ts
  frontend/src/components/MeetingTimeCard/MeetingTimeCard.styles.ts
  frontend/src/components/MeetingTimeCard/MeetingTimeOptionCard.tsx
  frontend/src/components/MeetingTimeCard/MeetingTimeRecommendCard.tsx
  frontend/src/components/_common/Dropdown/Dropdown.styles.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useMeetingTimeRecommendFilter/useMeetingTimeRecommendFilter.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/meeting/data/earliestAllAttendeeSchedules.json
  frontend/src/mocks/meeting/data/earliestPartialAttendeeSchedules.json
  frontend/src/mocks/meeting/data/longTermAllAttendeeSchedules.json
  frontend/src/mocks/meeting/data/longTermPartialAttendeeSchedules.json
  frontend/src/mocks/meeting/data/meetingAttendees.json
  frontend/src/mocks/meeting/meetingHandlers.ts
  frontend/src/mocks/meeting/recommendHandlers.ts
  frontend/src/pages/MeetingConfirmPage/MeetingTimeConfirmPage.styles.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.styles.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.tsx
  frontend/src/pages/MeetingConfirmPage/index.tsx
  frontend/src/pages/MeetingRecommendPage/MeetingRecommendPage.styles.ts
  frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.styles.ts
  frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/meeting/mutation.ts
  frontend/src/stores/servers/meeting/queries.ts
  frontend/src/styles/global.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#195 [FE] 로그아웃 기능 구현
  frontend/src/apis/attendee.ts
  frontend/src/apis/meetings.ts
  frontend/src/apis/users.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/contexts/AuthProvider.tsx
  frontend/src/hooks/useTimeRangeDropdown/constants.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/stores/servers/meeting/mutation.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🛠️ 픽스

#198 [FE] 불을 껐어요
  frontend/src/apis/meetings.ts
  frontend/src/components/Schedules/Picker/index.tsx
  frontend/src/components/Schedules/SchedulesViewer.tsx
  frontend/src/components/Time/Picker/index.tsx
  frontend/src/components/Time/Viewer/index.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/mocks/meeting/meetingHandlers.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🥵 핫픽스

#193 [FE] 카카오톡 공유하기 기능 구현 및 약속 생성 완료 페이지 리팩터링
  frontend/public/index.html
  frontend/src/assets/images/kakao.svg
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/pages/MeetingLinkSharePage/MeetingLinkSharePage.styles.ts
  frontend/src/pages/MeetingLinkSharePage/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#200 [BE] 로그아웃 쿠키에 Path가 누락된 문제를 해결
  backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
Labels: 🐈‍⬛ 백엔드, 🥵 핫픽스

#202 [BE] 약속 정보 조회시 주최자의 이름을 함께 반환
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/domain/attendee/Role.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/kr/momo/domain/attendee/RoleTest.java
Labels: 🐈‍⬛ 백엔드, 🛠️ 픽스

#184 [BE] 약속 확정 조회 기능 구현 및 확정 기능 수정
  backend/src/main/java/kr/momo/config/SchemaDefinitions.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingController.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/main/java/kr/momo/service/meeting/dto/ConfirmedMeetingResponse.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmRequest.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmResponse.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#204 [FE]약속 잠금 기능 구현 및 약속 추천 페이지 수정
  frontend/src/apis/meetings.ts
  frontend/src/apis/mettingRecommend.ts
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
  frontend/src/components/Schedules/AllSchedule.tsx
  frontend/src/components/Schedules/SchedulesViewer.tsx
  frontend/src/components/Schedules/SingleSchedule.tsx
  frontend/src/components/_common/Buttons/ToggleButton/index.tsx
  frontend/src/mocks/meeting/data/earliestAllAttendeeSchedules.json
  frontend/src/mocks/meeting/data/earliestPartialAttendeeSchedules.json
  frontend/src/mocks/meeting/data/longTermAllAttendeeSchedules.json
  frontend/src/mocks/meeting/data/longTermPartialAttendeeSchedules.json
  frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/stores/servers/meeting/mutation.ts
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#206 [FE] 쿼리키가 잘못 설정되어 있던 문제 해결 & 약속 확정 api 연결
  frontend/src/apis/meetingConfirm.ts
  frontend/src/apis/meetingRecommend.ts
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/hooks/useMeetingTimeRecommendFilter/useMeetingTimeRecommendFilter.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.tsx
  frontend/src/pages/MeetingConfirmPage/index.tsx
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/stores/servers/meeting/queries.ts
Labels: 🥵 핫픽스

#203 [BE] 로그 필터 구현
  backend/src/main/java/kr/momo/config/filter/FilterConfig.java
  backend/src/main/java/kr/momo/config/filter/LogFilter.java
  backend/src/main/java/kr/momo/config/filter/LogGenerator.java
  backend/src/main/java/kr/momo/config/filter/TraceIdGenerator.java
  backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#212 [ALL] 프론트엔드 배포 자동화 yml 파일 생성
  .github/workflows/frontend-cd.yml
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#209 [FE] 확정된 약속 정보 조회 API 데이터 Fetching
  frontend/src/apis/meetingConfirm.ts
  frontend/src/assets/images/momoCharacter.svg
  frontend/src/components/MeetingTicket/TicketInfo.tsx
  frontend/src/components/MeetingTicket/index.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/FixedMeetingTicketPage/FixedMeetingTicketPage.tsx
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.tsx
  frontend/src/router.tsx
  frontend/src/stores/servers/confirm/queries.ts
Labels: 🐈 프론트엔드, 🚀 기능

#211 [FE] TanStack Query devtools 설치
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#224 [BE] 확정 조회 문제 해결
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
  backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🛠️ 픽스

#218 [FE] 약속 시간 선택 default endTime 수정
  frontend/src/hooks/useTimeRangeDropdown/constants.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, ♻️ 리팩터링

#222 [FE] primary color 수정
  frontend/src/styles/tokens/colors.ts
Labels: 🐈 프론트엔드, 🎨 디자인, ♻️ 리팩터링

#228 [BE] 약속 생성 완료 시 생성된 약속의 정보를 응답
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateResponse.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
  backend/src/test/java/kr/momo/domain/timeslot/TimeslotTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#231 [BE] 운영 환경 추가로 인한 workflow 환경설정 추가
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-dev-ci.yml
  .github/workflows/backend-prod-cd.yml
  .github/workflows/backend-prod-ci.yml
Labels: 🐈‍⬛ 백엔드, ⚙️ 환경설정, 💣 (╮°-°)╮┳━┳, 😭 배고픔

#227 [BE] N+1 Query 문제를 해결
  backend/src/main/java/kr/momo/domain/schedule/ScheduleRepository.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#221 [FE] 캘린더 UI 개선
  frontend/src/components/_common/Calendar/Calendar.styles.ts
  frontend/src/components/_common/Calendar/index.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.ts
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
  frontend/src/styles/global.ts
  frontend/src/styles/tokens/colors.ts
  frontend/src/types/utility.ts
Labels: 🐈 프론트엔드, 🎨 디자인

#237 [FE] 모모 디자인 토큰 컬러 값 수정
  frontend/src/styles/tokens/colors.ts
Labels: 🐈 프론트엔드, 🎨 디자인

#240 [FE] CD 워크플로우에서 Self hosted runner 상세 태그 지정
  .github/workflows/frontend-cd.yml
Labels: 🐈 프론트엔드, 🥵 핫픽스, ⚙️ 환경설정

#232 [BE] Swagger API 문서 리팩터링
  backend/src/main/java/kr/momo/controller/annotation/ApiErrorResponse.java
  backend/src/main/java/kr/momo/controller/attendee/AttendeeControllerDocs.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
Labels: 🐈‍⬛ 백엔드, 📄 문서

#233 [BE] AvailableDates가 내부적으로 정렬된 상태를 유지하도록 개선
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDateRepository.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDates.java
  backend/src/main/java/kr/momo/domain/schedule/Schedule.java
  backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/domain/availabledate/AvailableDatesTest.java
  backend/src/test/java/kr/momo/domain/meeting/MeetingTest.java
  backend/src/test/java/kr/momo/domain/timeslot/TimeslotIntervalTest.java
  backend/src/test/java/kr/momo/domain/timeslot/TimeslotTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#223 [BE] 유효하지 않은 요청 시 상태코드 400 응답
  backend/src/main/java/kr/momo/controller/validator/DateFormatConstraint.java
  backend/src/main/java/kr/momo/controller/validator/DateFormatValidator.java
  backend/src/main/java/kr/momo/controller/validator/DateTimeFormatConstraint.java
  backend/src/main/java/kr/momo/controller/validator/DateTimeFormatValidator.java
  backend/src/main/java/kr/momo/controller/validator/TimeFormatConstraint.java
  backend/src/main/java/kr/momo/controller/validator/TimeFormatValidator.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeeName.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeePassword.java
  backend/src/main/java/kr/momo/exception/CustomProblemDetail.java
  backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginRequest.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingConfirmRequest.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateRequest.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/main/java/kr/momo/service/schedule/dto/DateTimesCreateRequest.java
  backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, 🐞 버그

#246 [FE] 00:00~01:00 시간 범위로 약속을 생성할 경우, 02:00까지 렌더링되는 문제 해결
  frontend/src/apis/meetings.ts
  frontend/src/apis/schedules.ts
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
  frontend/src/components/AttendeeTooltip/index.tsx
  frontend/src/components/MeetingTimeCard/MeetingTimeCard.styles.ts
  frontend/src/components/Schedules/AllSchedule.tsx
  frontend/src/components/Schedules/Picker/SchedulePicker.utils.ts
  frontend/src/components/Schedules/Picker/SchedulePickerContainer.tsx
  frontend/src/components/Schedules/Picker/index.tsx
  frontend/src/components/Schedules/SchedulesViewer.tsx
  frontend/src/components/Schedules/SingleSchedule.tsx
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/stores/servers/meeting/mutation.ts
  frontend/src/types/meeting.ts
  frontend/src/types/schedule.ts
Labels: 🐈 프론트엔드, 🎨 디자인, ♻️ 리팩터링

#250 [BE] 테스트시 로그 저장하지 않도록 수정
  backend/src/main/resources/logback-spring.xml
  backend/src/test/resources/application.yml
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#234 [FE] 입력 필드 유효성 검사 및 비밀번호 보기/숨기기 기능을 추가
  frontend/.storybook/main.ts
  frontend/src/assets/images/menu.svg
  frontend/src/assets/images/passwordHide.svg
  frontend/src/assets/images/passwordShow.svg
  frontend/src/components/PasswordInput/PasswordInput.stories.tsx
  frontend/src/components/PasswordInput/PasswordInput.styles.ts
  frontend/src/components/PasswordInput/index.tsx
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/components/_common/Field/Field.stories.tsx
  frontend/src/components/_common/Field/Field.styles.ts
  frontend/src/components/_common/Field/index.tsx
  frontend/src/components/_common/Input/Input.stories.tsx
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/components/_common/Input/index.tsx
  frontend/src/constants/inputFields.ts
  frontend/src/hooks/useInput/useInput.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.styles.ts
  frontend/src/pages/AttendeeLoginPage/AttendeeLoginPage.tsx
  frontend/src/pages/AttendeeLoginPage/index.tsx
  frontend/src/pages/CreateMeetingPage/CreateMeetingPage.styles.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/index.tsx
  frontend/src/router.tsx
  frontend/src/styles/tokens/colors.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인, ♻️ 리팩터링

#260 [BE] 약속 조회 응답 형식 수정
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🛠️ 픽스

#264 [BE] prod, dev CI 워크플로 병합 및 CD 잘못된 설정 수정
  .github/workflows/backend-ci.yml
  .github/workflows/backend-prod-cd.yml
  .github/workflows/backend-prod-ci.yml
Labels: 🐈‍⬛ 백엔드, ⚙️ 환경설정, ♻️ 리팩터링

#251 [FE] 확정된 약속 티켓 페이지 개선
  frontend/legacy/hooks/useScheduleTooltip/useScheduleTooltip.ts
  frontend/src/components/MeetingTicket/TicketInfo.tsx
  frontend/src/components/MeetingTicket/index.tsx
  frontend/src/components/MeetingTimeCard/MeetingTimeOptionCard.tsx
  frontend/src/components/MeetingTimeCard/MeetingTimeRecommendCard.tsx
  frontend/src/components/Schedules/AllSchedule.tsx
  frontend/src/components/Schedules/Picker/index.tsx
  frontend/src/components/Schedules/Schedules.util.ts
  frontend/src/components/Schedules/SingleSchedule.tsx
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/MeetingTicket.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/TicketInfo/TicketInfo.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/TicketInfo/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/index.tsx
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.tsx
  frontend/src/utils/date.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인, ♻️ 리팩터링

#262 [FE] ProvidePlugin 설정
  frontend/src/components/Schedules/SchedulesViewer.tsx
  frontend/webpack.common.js
Labels: 🐈 프론트엔드, 🛠️ 픽스, ⚙️ 환경설정

#254 [FE] 재사용할 수 있는 Text 컴포넌트 구현
  frontend/src/assets/images/information.svg
  frontend/src/components/_common/Text/Accent/Accent.styles.ts
  frontend/src/components/_common/Text/Accent/index.tsx
  frontend/src/components/_common/Text/Text.stories.tsx
  frontend/src/components/_common/Text/Text.styles.ts
  frontend/src/components/_common/Text/Text.types.ts
  frontend/src/components/_common/Text/index.tsx
  frontend/src/styles/tokens/typography.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#257 [FE] 약속 생성 완료 페이지 개선
  frontend/src/apis/meetings.ts
  frontend/src/assets/images/check.svg
  frontend/src/assets/images/copy.svg
  frontend/src/pages/MeetingLinkSharePage/MeetingLinkSharePage.styles.ts
  frontend/src/pages/MeetingLinkSharePage/index.tsx
  frontend/src/stores/servers/meeting/mutation.ts
  frontend/src/types/meeting.ts
  frontend/src/utils/clipboard.ts
  frontend/src/utils/groupDates.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인, ♻️ 리팩터링

#270 [FE] 입력 필드 버그 수정
  frontend/src/components/PasswordInput/index.tsx
  frontend/src/components/_common/Field/Field.styles.ts
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, 🛠️ 픽스

#272 [FE] 카카오톡 공유 로직 hook분리
  frontend/src/constants/kakao.ts
  frontend/src/hooks/useKakaoTalkShare/useKakaoTalkShare.ts
  frontend/src/pages/MeetingLinkSharePage/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#265 [FE] 약속 조회 페이지 테이블 UI 개선
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.stories.tsx
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.styles.ts
  frontend/src/components/AttendeeTooltip/AttendeeTooltip.utils.ts
  frontend/src/components/AttendeeTooltip/index.tsx
  frontend/src/components/Schedules/AllSchedule.tsx
  frontend/src/components/Schedules/Picker/SchedulePicker.utils.ts
  frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/ScheduleTableFrame/ScheduleDateDayList.tsx
  frontend/src/components/Schedules/ScheduleTableFrame/ScheduleTableFrame.style.ts
  frontend/src/components/Schedules/ScheduleTableFrame/ScheduleTimeList.tsx
  frontend/src/components/Schedules/ScheduleViewer/AllSchedules.tsx
  frontend/src/components/Schedules/ScheduleViewer/ScheduleTable.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/components/Schedules/ScheduleViewer/SingleSchedule.tsx
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/components/Schedules/Schedules.util.ts
  frontend/src/components/Schedules/SingleSchedule.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Tooltip/Tooltip.styles.ts
  frontend/src/constants/date.ts
  frontend/src/hooks/useDatePage/useDatePage.ts
  frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
  frontend/src/hooks/useTimePick/useTimePick.ts
  frontend/src/hooks/useTimePick/useTimePick.utils.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/stores/servers/meeting/queries.ts
Labels: 🐈 프론트엔드, 🎨 디자인

#286 [FE] 404 에러 페이지 작업 및 라우터 경로 수정
  frontend/src/assets/images/questionMomoCharacter.svg
  frontend/src/constants/routes/meeting.ts
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/pages/LandingPage/LandingPage.styles.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/NotFoundPage/NotFound.styles.ts
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/router.tsx
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#282 [FE] 약속 시간을 설정할 때 되는/안되는 시간을 구분해서 설정할 수 있도록 기능 추가
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/Schedules.util.ts
  frontend/src/hooks/usePagedTimePick/usePagedTimePick.ts
  frontend/src/hooks/useTimePick/useTimePick.ts
Labels: 🐈 프론트엔드, 🚀 기능

#284 [FE] 로그아웃 후 새로운 유저로 로그인을 한 후, 시간을 등록하려는 경우 이전 유저의 시간이 남아있던 문제 해결
  frontend/src/components/Schedules/SchedulePicker/SchedulePickerContainer.tsx
  frontend/src/stores/servers/meeting/queries.ts
Labels: 🐈 프론트엔드, 🥵 핫픽스

#291 [FE] 재사용할 수 있는 탭 컴포넌트 구현
  frontend/src/assets/images/attendeeCheck.svg
  frontend/src/components/_common/Buttons/Button/Button.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/components/_common/Buttons/TabButton/TabButton.stories.tsx
  frontend/src/components/_common/Buttons/TabButton/TabButton.styles.ts
  frontend/src/components/_common/Buttons/TabButton/TabButton.types.ts
  frontend/src/components/_common/Buttons/TabButton/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#281 [BE] 확정 약속 조회 시 hostName 정보 추가
  backend/src/main/java/kr/momo/controller/annotation/ApiErrorResponse.java
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
  backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/main/java/kr/momo/service/meeting/dto/ConfirmedMeetingResponse.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#287 [FE] 확정된 약속 취소 기능
  frontend/src/apis/meetingConfirm.ts
  frontend/src/assets/images/cancel.svg
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/FixedMeetingTicketPage.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/components/ActionButtonGroup/ActionButtonGroup.styles.ts
  frontend/src/pages/FixedMeetingTicketPage/components/ActionButtonGroup/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/TicketInfo/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/MeetingTicket/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/index.tsx
  frontend/src/stores/servers/confirm/mutations.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#301 [FE] Errorboundary 최상위 설정
  frontend/src/apis/_common/fetchClient.ts
  frontend/src/apis/meetingConfirm.ts
  frontend/src/apis/meetingRecommend.ts
  frontend/src/apis/meetings.ts
  frontend/src/apis/schedules.ts
  frontend/src/apis/users.ts
  frontend/src/components/_common/Header/index.tsx
  frontend/src/index.tsx
  frontend/src/layouts/GlobalLayout.tsx
  frontend/src/pages/AttendeeLoginPage/index.tsx
  frontend/src/pages/ErrorPage/ErrorPage.styles.ts
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/stores/servers/user/mutations.ts
  frontend/src/utils/responseError.ts
  frontend/webpack.prod.js
Labels: 🐈 프론트엔드, 🚀 기능

#304 [FE] 약속 추천 & 확정 페이지 디자인 수정
  frontend/src/pages/MeetingConfirmPage/MeetingTimeConfirmPage.styles.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions.tsx
  frontend/src/pages/MeetingConfirmPage/index.tsx
  frontend/src/pages/MeetingRecommendPage/MeetingRecommendPage.styles.ts
  frontend/src/pages/MeetingRecommendPage/components/MeetingTimeRecommends.tsx
  frontend/src/pages/MeetingRecommendPage/index.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.styles.ts
  frontend/src/pages/NotFoundPage/index.tsx
Labels: 🐈 프론트엔드, 🎨 디자인, 🏡 집 가고 싶음

#276 [BE] info 로그 필터링
  backend/src/main/java/kr/momo/config/filter/InfoLogFilter.java
  backend/src/main/resources/logback-spring.xml
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#273 [BE] JPA의 saveAll, deleteAll를 bulk query로 개선
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDate.java
  backend/src/main/java/kr/momo/domain/availabledate/AvailableDateBatchRepository.java
  backend/src/main/java/kr/momo/domain/schedule/Schedule.java
  backend/src/main/java/kr/momo/domain/schedule/ScheduleBatchRepository.java
  backend/src/main/java/kr/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/test/java/kr/momo/domain/availabledate/AvailableDateBatchRepositoryTest.java
  backend/src/test/java/kr/momo/domain/schedule/ScheduleBatchRepositoryTest.java
  backend/src/test/java/kr/momo/domain/schedule/ScheduleRepositoryTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#295 [BE] 쿠키 헤더의 SameSite 옵션을 변경
  backend/src/main/java/kr/momo/controller/CookieManager.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#307 [FE] 약속 조회 페이지 UI 개선
  frontend/src/assets/images/pen.svg
  frontend/src/assets/images/rotate.svg
  frontend/src/components/Schedules/DateControlButtons/DateControlButtons.styles.ts
  frontend/src/components/Schedules/DateControlButtons/index.tsx
  frontend/src/components/Schedules/ScheduleOverview/ScheduleOverview.styles.ts
  frontend/src/components/Schedules/ScheduleOverview/index.tsx
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/ScheduleViewer/SchedulesViewer.tsx
  frontend/src/components/Schedules/ScheduleViewer/SingleSchedule.tsx
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/components/_common/Buttons/Button/index.tsx
  frontend/src/components/_common/Spinner/Spinner.styles.ts
  frontend/src/components/_common/Spinner/index.tsx
  frontend/src/components/_common/Text/Accent/index.tsx
  frontend/src/components/_common/Text/Text.stories.tsx
  frontend/src/components/_common/Text/Text.styles.ts
  frontend/src/layouts/GlobalLayout.styles.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/MeetingTimePickPage/MeetingTimePickPage.styles.ts
  frontend/src/pages/MeetingTimePickPage/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/styles/global.ts
Labels: 🐈 프론트엔드, 🎨 디자인

#310 [FE] Accent props 구조의 변경 사항이 반영되지 않았던 문제 해결
  frontend/src/components/_common/Text/Accent/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#312 [FE] 사용자가 선택한 시간대를 강조할 수 있는 빗금 스타일 추가
  frontend/src/components/AttendeeTooltip/index.tsx
  frontend/src/components/Schedules/SchedulePicker/index.tsx
  frontend/src/components/Schedules/Schedules.styles.ts
  frontend/src/components/_common/Tooltip/Tooltip.styles.ts
  frontend/src/components/_common/Tooltip/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#292 [BE] 약속 추천 기능 리팩토링
  backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeeGroup.java
  backend/src/main/java/kr/momo/domain/schedule/DateAndTimeslot.java
  backend/src/main/java/kr/momo/domain/schedule/DateTimeInterval.java
  backend/src/main/java/kr/momo/domain/schedule/Schedule.java
  backend/src/main/java/kr/momo/domain/schedule/ScheduleRepository.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateScheduleSorter.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/EarliestFirstSorter.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/LongTermFirstSorter.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/RecommendedScheduleSortStandard.java
  backend/src/main/java/kr/momo/domain/timeslot/Timeslot.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/main/java/kr/momo/service/schedule/dto/DateTimesResponse.java
  backend/src/main/java/kr/momo/service/schedule/dto/RecommendedScheduleResponse.java
  backend/src/main/java/kr/momo/service/schedule/recommend/FilteredScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/recommend/ScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/recommend/ScheduleRecommenderFactory.java
  backend/src/main/java/kr/momo/service/schedule/recommend/TotalScheduleRecommender.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeeGroupTest.java
  backend/src/test/java/kr/momo/domain/schedule/DateAndTimeslotTest.java
  backend/src/test/java/kr/momo/domain/schedule/ScheduleRepositoryTest.java
  backend/src/test/java/kr/momo/domain/schedule/recommend/CandidateScheduleTest.java
  backend/src/test/java/kr/momo/domain/schedule/recommend/EarliestFirstSorterTest.java
  backend/src/test/java/kr/momo/domain/schedule/recommend/LongTermFirstSorterTest.java
  backend/src/test/java/kr/momo/fixture/AttendeeGroupFixture.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/recommend/ScheduleRecommenderFactoryTest.java
  backend/src/test/java/kr/momo/service/schedule/recommend/ScheduleRecommenderTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, 🛠️ 픽스, ♻️ 리팩터링, 🏡 집 가고 싶음

#308 [BE] 약속의 UUID 발급 방식을 개선
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/domain/meeting/MeetingRepository.java
  backend/src/main/java/kr/momo/domain/meeting/RandomUuidGenerator.java
  backend/src/main/java/kr/momo/domain/meeting/UuidGenerator.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/test/java/kr/momo/domain/meeting/fake/FakeUuidGenerator.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
Labels: 🐈‍⬛ 백엔드, ♻️ 리팩터링

#298 [BE] 요청 로그에 사용자 정보를 추가
  backend/src/main/java/kr/momo/config/WebConfig.java
  backend/src/main/java/kr/momo/config/filter/FilterConfig.java
  backend/src/main/java/kr/momo/config/filter/LogFilter.java
  backend/src/main/java/kr/momo/config/interceptor/JwtInterceptor.java
  backend/src/main/java/kr/momo/config/interceptor/LogGenerator.java
  backend/src/main/java/kr/momo/config/interceptor/LoggingInterceptor.java
  backend/src/main/java/kr/momo/config/interceptor/TraceIdGenerator.java
  backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, ♻️ 리팩터링

#319 [ALL] 프론트엔드 리소스 배포 dev, prod 구분
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
  frontend/package.json
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#317 [FE] 중복 선언된 alert 제거
  frontend/src/components/_common/Header/index.tsx
Labels: 🐈 프론트엔드, 🛠️ 픽스, 🏡 집 가고 싶음

#318 [FE] 추천 약속 리스트를 선택할 때 key 값을 startDate + index 대신 rank로 변경
  frontend/src/apis/meetingRecommend.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions/MeetingTimeOptions.styles.ts
  frontend/src/pages/MeetingConfirmPage/components/MeetingTimeOptions/index.tsx
Labels: 🐈 프론트엔드, 🛠️ 픽스

#322 [FE] dev 배포시에도 msw가 실행되었던 문제 해결
  frontend/package.json
  frontend/src/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#324 [FE] build:dev 스크립트에서 노드 환경을 production으로 수정
  frontend/package.json
  frontend/src/index.tsx
Labels: 🐈 프론트엔드, 🥵 핫픽스

#327 [FE] build:dev 스크립트에서 노드 환경을 production으로 수정
  frontend/package.json
Labels: 🐈 프론트엔드, 🥵 핫픽스
