Repository woowacourse-teams/2024-momo, pull requests merged in 2024-09, with the labels that each got.

#329 [ALL] frontend-prod-cd.yml 파일의 detect-change job 수정
  .github/workflows/frontend-prod-cd.yml
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#340 [FE] 시간 선택 Dropdown value 수정
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.test.ts
  frontend/src/hooks/useTimeRangeDropdown/useTimeRangeDropdown.utils.ts
Labels: 🐈 프론트엔드, 🛠️ 픽스

#342 [FE] 비밀번호 입력 간소화 및 모바일 숫자 키패드를 적용
  frontend/src/constants/inputFields.ts
  frontend/src/hooks/useInput/useInput.ts
  frontend/src/pages/AttendeeLoginPage/index.tsx
  frontend/src/pages/CreateMeetingPage/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, ♻️ 리팩터링

#344 [BE] 비밀번호 검증 로직 변경
  backend/src/main/java/kr/momo/domain/attendee/AttendeePassword.java
  backend/src/main/java/kr/momo/exception/code/AttendeeErrorCode.java
  backend/src/main/java/kr/momo/service/attendee/dto/AttendeeLoginRequest.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeePasswordTest.java
  backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능, ♻️ 리팩터링

#349 [FE] CopyWebpackPlugin을 사용하여 favicon 적용 문제 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
Labels: 🐈 프론트엔드, 🛠️ 픽스, ⚙️ 환경설정

#330 [ALL] frontend-prod-cd.yml 파일의 detect-change job 수정
  .github/workflows/frontend-prod-cd.yml
  frontend/package.json
  frontend/src/index.tsx
Labels: 🐈 프론트엔드, ⚙️ 환경설정

#346 [FE] 런칭데이에서 받은 달력 UI 피드백 반영
  frontend/legacy/Calendar/Calendar.stories.tsx
  frontend/legacy/Calendar/Calendar.styles.ts
  frontend/legacy/Calendar/CalendarDate.styles.ts
  frontend/legacy/Calendar/Date/RangeCalendarDate.tsx
  frontend/legacy/Calendar/Date/SingleCalendarDate.tsx
  frontend/legacy/Calendar/index.tsx
  frontend/legacy/hooks/useCalendarInfo/useCalendarInfo.ts
  frontend/legacy/hooks/useCalendarInfo/useCalendarInfo.utils.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MeetingCalendar/Date/Date.styles.ts
  frontend/src/components/MeetingCalendar/Date/Date.utils.ts
  frontend/src/components/MeetingCalendar/Date/DateAdditionalText.tsx
  frontend/src/components/MeetingCalendar/Date/RangeDate.tsx
  frontend/src/components/MeetingCalendar/Date/SingleDate.tsx
  frontend/src/components/MeetingCalendar/Header/MeetingCalendarHeader.styles.ts
  frontend/src/components/MeetingCalendar/Header/index.tsx
  frontend/src/components/MeetingCalendar/Weekdays/MeetingCalendarWeekdays.styles.ts
  frontend/src/components/MeetingCalendar/Weekdays/index.tsx
  frontend/src/components/_common/Buttons/TabButton/index.tsx
  frontend/src/components/_common/Calendar/Body/index.tsx
  frontend/src/components/_common/Calendar/Calendar.stories.tsx
  frontend/src/components/_common/Calendar/Calendar.styles.ts
  frontend/src/components/_common/Calendar/Header/index.tsx
  frontend/src/components/_common/Calendar/Weekdays/index.tsx
  frontend/src/components/_common/Calendar/index.tsx
  frontend/src/contexts/CalendarProvider.tsx
  frontend/src/hooks/useCalendar/useCalendar.ts
  frontend/src/hooks/useCalendar/useCalendar.utils.ts
  frontend/src/hooks/useCalendarContext/useCalendarContext.ts
  frontend/src/hooks/useCalendarInfo/useCalendarInfo.utils.ts
  frontend/src/hooks/useDateSelect/useDateSelect.ts
  frontend/src/hooks/useDateSelect/useDateSelect.utils.ts
  frontend/src/pages/CreateMeetingPage/index.tsx
  frontend/src/types/calendar.ts
  frontend/src/utils/date.ts
  frontend/src/utils/typeGuards.ts
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#359 [FE] 체크박스 공통 컴포넌트 구현
  frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/_common/Checkbox/Checkbox.styles.ts
  frontend/src/components/_common/Checkbox/index.tsx
Labels: 🐈 프론트엔드, 🚀 기능, 🎨 디자인

#365 [FE] 리소스를 최적화 및 번들 크기 감소
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/fonts/Pretendard-Black.woff2
  frontend/src/assets/fonts/Pretendard-Bold.subset.woff2
  frontend/src/assets/fonts/Pretendard-Bold.woff2
  frontend/src/assets/fonts/Pretendard-ExtraBold.woff2
  frontend/src/assets/fonts/Pretendard-ExtraLight.woff2
  frontend/src/assets/fonts/Pretendard-Light.subset.woff2
  frontend/src/assets/fonts/Pretendard-Light.woff2
  frontend/src/assets/fonts/Pretendard-Medium.subset.woff2
  frontend/src/assets/fonts/Pretendard-Medium.woff2
  frontend/src/assets/fonts/Pretendard-Regular.subset.woff2
  frontend/src/assets/fonts/Pretendard-Regular.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.woff2
  frontend/src/assets/fonts/Pretendard-Thin.woff2
  frontend/src/assets/images/kakao.svg
  frontend/src/assets/images/logo.svg
  frontend/src/assets/images/logoSunglass.svg
  frontend/src/assets/images/momoCharacter.svg
  frontend/src/assets/images/momoPageLoading.json
  frontend/src/assets/images/questionMomoCharacter.svg
  frontend/src/assets/images/sadMomoCharacter.svg
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/PageMoveLoading/PageMoveLoading.style.ts
  frontend/src/components/_common/PageMoveLoading/index.tsx
  frontend/src/pages/FixedMeetingTicketPage/components/UnconfirmedMessage/index.tsx
  frontend/src/router.tsx
  frontend/src/styles/fonts.ts
  frontend/src/types/images.d.ts
  frontend/webpack.common.js
Labels: 🐈 프론트엔드, ⚙️ 환경설정, ♻️ 리팩터링

#345 [BE] 참가자 비밀번호 암호화 적용
  backend/build.gradle
  backend/src/main/java/kr/momo/config/PasswordEncoderConfig.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeePassword.java
  backend/src/main/java/kr/momo/domain/attendee/AttendeeRawPassword.java
  backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateRequest.java
  backend/src/test/java/kr/momo/controller/attendee/AttendeeControllerTest.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/controller/schedule/ScheduleControllerTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeePasswordTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeeRawPasswordTest.java
  backend/src/test/java/kr/momo/domain/attendee/AttendeeTest.java
  backend/src/test/java/kr/momo/fixture/AttendeeFixture.java
  backend/src/test/java/kr/momo/service/attendee/AttendeeServiceTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#369 [BE] 비밀번호 마이그레이션 추가
  backend/src/main/java/kr/momo/controller/attendee/AttendeeController.java
  backend/src/main/java/kr/momo/domain/attendee/Attendee.java
  backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
Labels: 🐈‍⬛ 백엔드, 🥵 핫픽스, 💣 (╮°-°)╮┳━┳

#367 [BE] 날짜만 선택가능한 약속 기능들 추가
  backend/src/main/java/kr/momo/controller/meeting/MeetingControllerDocs.java
  backend/src/main/java/kr/momo/controller/schedule/ScheduleController.java
  backend/src/main/java/kr/momo/controller/schedule/ScheduleControllerDocs.java
  backend/src/main/java/kr/momo/domain/meeting/ConfirmedMeeting.java
  backend/src/main/java/kr/momo/domain/meeting/Meeting.java
  backend/src/main/java/kr/momo/domain/meeting/MeetingType.java
  backend/src/main/java/kr/momo/domain/schedule/DateInterval.java
  backend/src/main/java/kr/momo/domain/schedule/DateTimeInterval.java
  backend/src/main/java/kr/momo/domain/schedule/RecommendInterval.java
  backend/src/main/java/kr/momo/domain/schedule/Schedule.java
  backend/src/main/java/kr/momo/domain/schedule/recommend/CandidateSchedule.java
  backend/src/main/java/kr/momo/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/momo/exception/code/MeetingErrorCode.java
  backend/src/main/java/kr/momo/service/meeting/MeetingConfirmService.java
  backend/src/main/java/kr/momo/service/meeting/MeetingService.java
  backend/src/main/java/kr/momo/service/meeting/dto/ConfirmedMeetingResponse.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingCreateRequest.java
  backend/src/main/java/kr/momo/service/meeting/dto/MeetingResponse.java
  backend/src/main/java/kr/momo/service/schedule/ScheduleService.java
  backend/src/main/java/kr/momo/service/schedule/dto/RecommendedSchedulesResponse.java
  backend/src/main/java/kr/momo/service/schedule/recommend/FilteredScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/recommend/ScheduleRecommender.java
  backend/src/main/java/kr/momo/service/schedule/recommend/TotalScheduleRecommender.java
  backend/src/test/java/kr/momo/controller/meeting/MeetingControllerTest.java
  backend/src/test/java/kr/momo/domain/meeting/ConfirmedMeetingTest.java
  backend/src/test/java/kr/momo/domain/meeting/MeetingTypeTest.java
  backend/src/test/java/kr/momo/fixture/MeetingFixture.java
  backend/src/test/java/kr/momo/service/meeting/MeetingConfirmServiceTest.java
  backend/src/test/java/kr/momo/service/meeting/MeetingServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/ScheduleServiceTest.java
  backend/src/test/java/kr/momo/service/schedule/recommend/ScheduleRecommenderTest.java
Labels: 🐈‍⬛ 백엔드, 🚀 기능

#375 [BE] replica로 업데이트 쿼리 날아가던 오류 수정
  backend/src/main/java/kr/momo/config/RoutingDataSource.java
  backend/src/main/java/kr/momo/service/attendee/AttendeeService.java
Labels: 🐈‍⬛ 백엔드, 🥵 핫픽스

#378 [FE] 깃허브 워크플로우에서 webpack-bundle-analyzer가 실행됐던 문제 해결
  frontend/package.json
  frontend/webpack.common.js
Labels: 🥵 핫픽스

#380 [ALL] frontend CI 수정
  .github/workflows/frontend-ci.yml
Labels: 🐈 프론트엔드, ♻️ 리팩터링
